development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  #url: redis://localhost:6379/1
  url: redis://redistogo:068564caf9d58bf9d65fbe55a134cd0e@koi.redistogo.com:10024/
  channel_prefix: thestrew_production
